### ISSUE TITLE
执行时出现了问题

### ISSUE THREAD

**Issue by Thump123** [whwlsfb/JDumpSpider#8]
java8 -jar JDumpSpider-1.1-SNAPSHOT-full.jar ./heapdump
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "d"
        at cn.wanghw.Main.getFileVersion(Main.java:111)
        at cn.wanghw.Main.call(Main.java:58)
        at cn.wanghw.Main.main(Main.java:29)
Caused by: java.lang.NumberFormatException: For input string: "d"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at cn.wanghw.Main.getFileVersion(Main.java:109)
        ... 2 more

D:\工具\mat>java -jar JDumpSpider-1.1-SNAPSHOT-full.jar ./heapdump
Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "d"
        at cn.wanghw.Main.getFileVersion(Main.java:111)
        at cn.wanghw.Main.call(Main.java:58)
        at cn.wanghw.Main.main(Main.java:29)
Caused by: java.lang.NumberFormatException: For input string: "d"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at cn.wanghw.Main.getFileVersion(Main.java:109)
        ... 2 more

**Comment by whwlsfb** [comment]
这个heapdump文件可能是压缩的，建议先解压再尝试

**Comment by R4gd0ll** [comment]
下载下来直接是heapdump文件，使用工具也出现了相同的报错，如何解压缩呢？

**Comment by whwlsfb** [comment]
> 下载下来直接是heapdump文件，使用工具也出现了相同的报错，如何解压缩呢？

给文件名加一个.zip后缀，然后用各种解压缩软件解压
